version: '3.8'
services:
  task-service:
    build:
      context: .
      dockerfile: ./task-service/Dockerfile
    ports:
      - 8080:8080
    environment:
      - RABBIT_USER=myuser
      - RABBIT_PASSWORD=mypassword
      - RABBIT_HOST=rabbitmq:5672
      - RABBIT_VHOST=/

      - SERVER_ADDRESS=:8080
      - SERVER_READ_TIMEOUT=5s
      - SERVER_WRITE_TIMEOUT=5s
      - SERVER_IDLE_TIMEOUT=30s
    depends_on:
      rabbitmq:
        condition: service_healthy
      code-processor:
        condition: service_started
      db:
        condition: service_healthy
      task-service-migrations:
        condition: service_completed_successfully
      redis:
        condition: service_healthy

  code-processor:
    build:
      context: .
      dockerfile: ./code-processor/Dockerfile
    ports:
      - 8081:8081
    environment:
      - RABBIT_USER=myuser
      - RABBIT_PASSWORD=mypassword
      - RABBIT_HOST=rabbitmq:5672
      - RABBIT_VHOST=/
    # volume используется для доступа к docker daemon
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      rabbitmq:
        condition: service_healthy

  db:
    image: postgres:15-alpine
    container_name: db
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: tasks
    healthcheck:
      test: [ "CMD-SHELL", "sh -c 'pg_isready -U postgres -d tasks'" ]
      interval: 5s
      timeout: 10s
      retries: 5
      start_period: 10s

  # Вариант запуска миграций в своем контейнере
  task-service-migrations:
    build:
      context: .
      dockerfile: ./task-service/migrations/Dockerfile
    environment:
      - DBHOST=db
      - DBPORT=5432
      - DBUSER=postgres
      - DBPASSWORD=postgres
      - DBNAME=tasks
      - DBSSL=disable
    depends_on:
      db:
        condition: service_healthy

  redis:
    image: redis:7.4.2-alpine
    container_name: redis
    ports:
      - "6379:6379"
    environment:
      REDIS_PASSWORD: redis
    healthcheck:
      test: ["CMD-SHELL", "sh -c 'redis-cli ping'"]
      interval: 10s
      timeout: 5s
      retries: 3
    

  rabbitmq:
    image: rabbitmq:4.0-management
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      RABBITMQ_DEFAULT_USER: myuser
      RABBITMQ_DEFAULT_PASS: mypassword
      RABBITMQ_DEFAULT_VHOST: /
    # volume используется для доступа к файлам конфигурации rabbit
    volumes:
      - ./rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf:ro
      - ./rabbitmq_definitions.json:/etc/rabbitmq/rabbitmq_definitions.json:ro
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 10s
      timeout: 10s
      retries: 3

  app_test:
    build: ./tests
    container_name: app_test
    environment:
      BASE_URL: http://task-service:8080
    depends_on:
      task-service:
        condition: service_started
      code-processor:
        condition: service_started
    profiles: [ 'test' ]
