# my global config
global:
  scrape_interval: 15s
  evaluation_interval: 15s 


scrape_configs:
  - job_name: "task-service"
    static_configs:
      - targets: ["task-service:8080"]
  - job_name: "prometheus"
    static_configs:
      - targets: ["prometheus:9090"]
    