http_server:
  address: :8080
  read_timeout: 5s
  write_timeout: 5s
  idle_timeout: 30s

rabbitmq:
  user: myuser
  password: mypassword
  host: rabbitmq:5672
  vhost: /

postgres:
  host: db
  port: 5432
  user: postgres
  password: postgres
  db_name: tasks

redis:
  host: redis
  port: 6379
  password: redis
  TTL: 30m
  write_timeout: 3s
  read_timeout: 2s

logger:
  format: text
  level: info
  directory: /app/logs