basePath: /
definitions:
  types.CreateTaskResponse:
    properties:
      task_id:
        type: string
    type: object
  types.GetResultResponse:
    properties:
      result:
        items:
          type: integer
        type: array
    type: object
  types.GetStatusResponse:
    properties:
      status:
        type: string
    type: object
host: localhost:8080
info:
  contact: {}
  description: This is a sample server.
  title: Task-server API
  version: "1.0"
paths:
  /result/{task_id}:
    get:
      description: Returns the result of a completed task by its ID
      parameters:
      - description: Task ID
        format: uuid
        in: path
        name: task_id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/types.GetResultResponse'
        "400":
          description: Invalid task ID format or internal error
          schema:
            type: string
        "404":
          description: Task not found
          schema:
            type: string
      summary: Get task result
      tags:
      - task
  /status/{task_id}:
    get:
      description: Returns the current status of a task by its ID
      parameters:
      - description: Task ID
        format: uuid
        in: path
        name: task_id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/types.GetStatusResponse'
        "400":
          description: Invalid task ID format
          schema:
            type: string
        "404":
          description: Task not found
          schema:
            type: string
        "500":
          description: Internal server error
          schema:
            type: string
      summary: Get task status
      tags:
      - task
  /task:
    post:
      description: Creates a new task and returns task ID
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/types.CreateTaskResponse'
        "400":
          description: Invalid request
          schema:
            type: string
        "500":
          description: Internal server error
          schema:
            type: string
      summary: Create a task
      tags:
      - task
swagger: "2.0"
