name: Docker Compose CI

on:
  push:
    branches:
      - dz
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.24'

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Install Make
      run: sudo apt-get install make

    - name: Run Tests
      run: make test

    - name: Start Services
      run: make start_services

    - name: Shut Down Docker Compose
      if: always()
      run: make stop_services